name: Build unity app

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      define_symbols:
        description: "Scripting Define Symbols"
        required: false
        default: "SYMBOL_A;SYMBOL_B;SYMBOL_C;"
      enable_ios_build:
        type: boolean
        description: Build for iOS
        required: true
        default: true
      enable_android_build:
        type: boolean
        description: Build for Android
        required: true
        default: true

# --------
# Secrets
# --------
#  - UNITY_EMAIL: xxxxx@example.com
#  - UNITY_PASSWORD: xxxxx@example.com's password
#  - UNITY_LICENSE: cat '/Library/Application Support/Unity/Unity_lic.ulf' | pbcopy
#
#  for Android
#    - ANDROID_KEYSTORE_BASE64: $(cat xxxx.keystore | base64)
#    - ANDROID_KEYSTORE_PASS: aaaaaa
#    - ANDROID_KEY_ALIAS_NAME: bbbbbb
#    - ANDROID_KEY_ALIAS_PASS: cccccc
#
#  for iOS
#    - APPLE_DEVELOPER_TEAM_ID: ddddddd
#    - APPLE_PROVISIONING_PROFILE_ID: eee-ee-eee-eeee-eeee
#    - APPLE_PROVISIONING_PROFILE_BASE64: $(cat /path/to/ad-hoc.mobileprovision | base64)
#    - APPLE_BUILD_CERTIFICATE_P12_BASE64: $(cat /path/to/cert.p12 | base64)
#    - APPLE_P12_PASSWORD: ffffffffff
#    - APPLE_KEYCHAIN_PASSWORD: gggggggggggg
#    - APPLE_EXPORT_OPTIONS_PLIST_BASE64: $(cat /path/to/ExportOptions.plist | base64)
#    - APPLE_CODE_SIGN_IDENTITY=iPhone Distribution: XXXXXXX (YYYYYYYYY)

jobs:
  build-android:
    name: Run Unity Androlid build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    if: ${{ github.event.inputs.enable_android_build == 'true' }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Use caches
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # /Applications/Unity/Hub/Editor/${UNITY_CLI_VERSION}/Unity.app/Contents/MacOS/Unity \
      #   -quit \
      #   -batchmode -executeMethod K5unity.Editor.CustomBuild.PrepareForGoogle \
      #   -logFile ${PROJECT_PATH}/1_prepare_for_google.log \
      #   -projectPath ${PROJECT_PATH} \
      #   -defineSymbols ${SYMBOLS}
      # @see https://game.ci/docs/github/builder/
      - name: Preparation
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          # @see https://docs.unity3d.com/ScriptReference/BuildTarget.html
          targetPlatform: Android
          unityVersion: 2021.3.36f1
          buildMethod: K5unity.Editor.CustomBuild.PrepareForGoogle
          customParameters: -defineSymbols ${{ github.event.inputs.define_symbols }}

      - name: Restore keystore file
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > build.keystore

      - name: Test keystore file
        env:
          KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          KEY_ALIAS_NAME: ${{ secrets.ANDROID_KEY_ALIAS_NAME }}
        run: |
          keytool -exportcert -alias $KEY_ALIAS_NAME --storepass $KEYSTORE_PASS -keystore build.keystore | openssl sha1 -binary | openssl base64

      # /Applications/Unity/Hub/Editor/${UNITY_CLI_VERSION}/Unity.app/Contents/MacOS/Unity \
      #   -quit \
      #   -batchmode -executeMethod K5unity.Editor.CustomBuild.BuildForGoogle \
      #   -logFile ${PROJECT_PATH}/2_build_for_google.log \
      #   -projectPath ${PROJECT_PATH} \
      #   -keystorePass ${KEYSTORE_PASS} \
      #   -keyAliasName ${KEY_ALIAS_NAME} \
      #   -keyAliasPass ${KEY_ALIAS_PASS} \
      #   -defineSymbols ${SYMBOLS}
      - name: Build
        uses: game-ci/unity-builder@v4
        id: buildStep
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          # @see https://docs.unity3d.com/ScriptReference/BuildTarget.html
          targetPlatform: Android
          unityVersion: 2021.3.36f1
          allowDirtyBuild: true
          buildMethod: K5unity.Editor.CustomBuild.BuildForGoogle
          androidKeystoreName: build.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEY_ALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEY_ALIAS_PASS }}
          customParameters: |
            -defineSymbols ${{ github.event.inputs.define_symbols }} \
            -keystoreName build.keystore \
            -keystorePass ${{ secrets.ANDROID_KEYSTORE_PASS }} \
            -keyAliasName ${{ secrets.ANDROID_KEY_ALIAS_NAME }} \
            -keyAliasPass ${{ secrets.ANDROID_KEY_ALIAS_PASS }}"

      - name: list
        run: |
            echo "$ ls"
            ls -al
            echo 'Project Version: ${{ steps.buildStep.outputs.buildVersion }}'
            echo 'Android Version Code: ${{ steps.buildStep.outputs.androidVersionCode }}'
            echo 'Build Step Exit Code: ${{ steps.buildStep.outputs.engineExitCode }}'

      - name: Upload Android binary
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: "binary.aab"
          retention-days: 5

  build-ios-unity:
    name: Run Unity iOS build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    if: ${{ github.event.inputs.enable_ios_build == 'true' }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Use caches
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # /Applications/Unity/Hub/Editor/${UNITY_CLI_VERSION}/Unity.app/Contents/MacOS/Unity \
      #   -quit \
      #   -batchmode -executeMethod K5unity.Editor.CustomBuild.PrepareForApple \
      #   -logFile ${PROJECT_PATH}/1_prepare_for_apple.log \
      #   -projectPath ${PROJECT_PATH} \
      #   -defineSymbols ${SYMBOLS}
      # @see https://game.ci/docs/github/builder/
      - name: Preparation
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          # @see https://docs.unity3d.com/ScriptReference/BuildTarget.html
          targetPlatform: iOS
          unityVersion: 2021.3.36f1
          buildMethod: K5unity.Editor.CustomBuild.PrepareForApple
          customParameters: -defineSymbols ${{ github.event.inputs.define_symbols }}

      # /Applications/Unity/Hub/Editor/${UNITY_CLI_VERSION}/Unity.app/Contents/MacOS/Unity \
      #   -quit \
      #   -batchmode -executeMethod K5unity.Editor.CustomBuild.BuildForApple \
      #   -logFile ${PROJECT_PATH}/2_build_for_apple.log \
      #   -projectPath ${PROJECT_PATH} \
      #   -keystorePass ${KEYSTORE_PASS} \
      #   -keyAliasName ${KEY_ALIAS_NAME} \
      #   -keyAliasPass ${KEY_ALIAS_PASS} \
      #   -defineSymbols ${SYMBOLS}
      - name: Build
        uses: game-ci/unity-builder@v4
        id: buildStep
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          # @see https://docs.unity3d.com/ScriptReference/BuildTarget.html
          targetPlatform: iOS
          unityVersion: 2021.3.36f1
          allowDirtyBuild: true
          buildMethod: K5unity.Editor.CustomBuild.BuildForApple
          customParameters: "-appleDeveloperTeamId ${{ secrets.APPLE_DEVELOPER_TEAM_ID }} -provisioningProfileId ${{ secrets.APPLE_PROVISIONING_PROFILE_ID }} -defineSymbols ${{ github.event.inputs.define_symbols }}"

      - name: list
        run: |
            echo "$ ls"
            ls -al
            # cat ProjectSettings/ProjectSettings.asset
            echo 'Project Version: ${{ steps.buildStep.outputs.buildVersion }}'
            echo 'Android Version Code: ${{ steps.buildStep.outputs.androidVersionCode }}'
            echo 'Build Step Exit Code: ${{ steps.buildStep.outputs.engineExitCode }}'
            cat XcodeProject/Unity-iPhone.xcodeproj/project.pbxproj | grep 'PROVISIONING_PROFILE_APP'
            cat XcodeProject/Unity-iPhone.xcodeproj/project.pbxproj | grep 'DEVELOPMENT_TEAM'
            cat XcodeProject/Unity-iPhone.xcodeproj/project.pbxproj | grep -E 'PROVISIONING_PROFILE_APP|DEVELOPMENT_TEAM'

      - name: Upload xcode workspace
        uses: actions/upload-artifact@v4
        with:
          name: xcworkspace
          path: |
            XcodeProject
          retention-days: 5

  build-ios-native:
    name: Run iOS Native build
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md
    needs: build-ios-unity
    environment: ${{ github.event.inputs.environment }}
    if: ${{ github.event.inputs.enable_ios_build == 'true' }}
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app
    steps:

      - name: Download xcode workspace
        uses: actions/download-artifact@v4
        with:
          name: xcworkspace

      - name: Setup
        env:
          P12_PASSWORD: ${{ secrets.APPLE_P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
          EXPORT_OPTIONS_PLIST_BASE64: ${{ secrets.APPLE_EXPORT_OPTIONS_PLIST_BASE64 }}
          BUILD_CERTIFICATE_P12_BASE64: ${{ secrets.APPLE_BUILD_CERTIFICATE_P12_BASE64 }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPLE_PROVISIONING_PROFILE_BASE64 }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Restore certificate, provisioning profile and export options from secrets
          echo -n "$BUILD_CERTIFICATE_P12_BASE64"   | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          echo -n "$EXPORT_OPTIONS_PLIST_BASE64"    | base64 --decode -o ExportOptions.plist

          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Import provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: list(1)
        run: |
          echo "$ ls"
          ls -al

      - name: Xcode Archive
        env:
          APPLE_CODE_SIGN_IDENTITY: ${{ secrets.APPLE_CODE_SIGN_IDENTITY }}
        run: |
          xcodebuild \
          clean archive \
          -project Unity-iPhone.xcodeproj \
          -scheme Unity-iPhone \
          -destination 'generic/platform=iOS' \
          -configuration Release \
          -archivePath ./build/App.xcarchive \
          CODE_SIGN_IDENTITY="${APPLE_CODE_SIGN_IDENTITY}"

      - name: Xcode Export
        run: |
          xcodebuild \
          -exportArchive \
          -archivePath ./build/App.xcarchive  \
          -exportPath ./build  \
          -exportOptionsPlist ExportOptions.plist

      - name: list(2)
        run: |
          echo "$ ls"
          ls -al
          ls -al build

      - name: Upload iOS binary
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: |
            build/*.ipa
            build/*.dSYM.zip
          retention-days: 5
