name: Build unity app for development

on:
  workflow_dispatch:
    inputs:
      define_symbols:
        description: "Scripting Define Symbols"
        required: false
        default: "SYMBOL_A;SYMBOL_B;SYMBOL_C;"
      enable_ios_build:
        type: boolean
        description: Build for iOS
        required: false
        default: true
      enable_android_build:
        type: boolean
        description: Build for Android
        required: false
        default: true
      enable_auto_assign_version_code:
        type: boolean
        description: Use github.run_number as version code
        required: false
        default: true

jobs:
  build-ios:
    name: Build Unity iOS app
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/_ios.yml
    if: ${{ github.event.inputs.enable_android_build == 'true' }}
    with:
      environment: development
      define_symbols: ${{ github.event.inputs.define_symbols }}
      enable_auto_assign_version_code: ${{ github.event.inputs.enable_auto_assign_version_code }}
    secrets: inherit
  build-andorid:
    name: Build Unity Android app
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/_android.yml
    if: ${{ github.event.inputs.enable_android_build == 'true' }}
    with:
      environment: development
      define_symbols: ${{ github.event.inputs.define_symbols }}
      enable_auto_assign_version_code: ${{ github.event.inputs.enable_auto_assign_version_code }}
    secrets: inherit
